// File generated by FlutterFire CLI.
// To regenerate this file, run `flutterfire configure --project=<firebase_project_id>`

import 'dart:io';
import 'package:flutter/foundation.dart' show kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Qx2C44x076nGEfMNkKVAtQHN5KzhQKw',
    appId: '1:680919552840:web:5c6c58b53027844afa997d',
    messagingSenderId: '680919552840',
    projectId: 'taxsisub',
    authDomain: 'taxsisub.firebaseapp.com',
    storageBucket: 'taxsisub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimPK2KGm4p9W6oXM315vI8PQwA2Bs0Xw',
    appId: '1:680919552840:android:de8bbfad764c55b6fa997d',
    messagingSenderId: '680919552840',
    projectId: 'taxsisub',
    storageBucket: 'taxsisub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6OXI8VcUxFw5yrp-jr9H0abfgPsTyq3g',
    appId: '1:680919552840:ios:ce0f94df0bc5b53afa997d',
    messagingSenderId: '680919552840',
    projectId: 'taxsisub',
    storageBucket: 'taxsisub.firebasestorage.app',
    iosBundleId: 'com.example.taxsiSub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6OXI8VcUxFw5yrp-jr9H0abfgPsTyq3g',
    appId: '1:680919552840:ios:ce0f94df0bc5b53afa997d',
    messagingSenderId: '680919552840',
    projectId: 'taxsisub',
    storageBucket: 'taxsisub.firebasestorage.app',
    iosBundleId: 'com.example.taxsiSub',
  );

  // Import needed for TargetPlatform
  static TargetPlatform get defaultTargetPlatform {
    if (Platform.isAndroid) return TargetPlatform.android;
    if (Platform.isIOS) return TargetPlatform.iOS;
    if (Platform.isMacOS) return TargetPlatform.macOS;
    if (Platform.isWindows) return TargetPlatform.windows;
    if (Platform.isLinux) return TargetPlatform.linux;
    throw UnsupportedError('Unknown platform');
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Qx2C44x076nGEfMNkKVAtQHN5KzhQKw',
    appId: '1:680919552840:web:8375c0b8c4a18329fa997d',
    messagingSenderId: '680919552840',
    projectId: 'taxsisub',
    authDomain: 'taxsisub.firebaseapp.com',
    storageBucket: 'taxsisub.firebasestorage.app',
  );

}